/* Documentation
- https://github.com/acornjs/acorn; to parse the p5 sketches
- https://github.com/benjamn/recast; to visit the AST generated by acorn
- https://astexplorer.net/; to figure out the types of the AST nodes
- https://saehm.github.io/DruidJS/api/classes/TSNE.html; for the T-SNE embedding
*/
import * as acorn from "acorn"; // to parse the artwork
import * as recast from "recast"; // to visit the artwork AST
import * as fs from 'node:fs'; // to read and write files and folders
import * as druid from "@saehrimnir/druidjs"; // for t-SNE
import { fileURLToPath } from 'url';
import { realpathSync } from 'fs';
import path from 'path';


const modulePath = fileURLToPath(import.meta.url);
const mainPath = process.argv[1];
const artfolder = "../art-in-swh/examples/74_examples/"
//const artfolder = "./lotsofartworks/"
const p5API = JSON.parse(fs.readFileSync('./p5API.json'));
const p5APIModules = JSON.parse(fs.readFileSync('./p5API_classes.json'));
const artwork_classification = JSON.parse(fs.readFileSync('../art-in-swh/examples/74_examples_manual_classification.json'));
const pathsToArtFiles = []

if (realpathSync(modulePath) === realpathSync(mainPath)) {
    console.log('This module is being run as the main script.');
    // Run main functionality here
    main();
}


async function main() {
    /**
     * fetching and storing p5 functions needs to be done only once; that's why it's commented */
    // await storeP5API()

    /**
     * get the paths to all artwork source code files */
    let allpaths = getArtFilesInFolder(artfolder)
    console.log(pathsToArtFiles.length)

    /**
     * load the p5 function names in the p5map dictionnary */
    let p5map = new Map()
    for (let x in p5API) {
        p5map.set(p5API[x][0], p5API[x][1])
    }
    /**
     * store the p5 usage in artwork source code files */
    getP5Usage(p5map, pathsToArtFiles, "p5InArtworks74-classes.json")

    /**
     * load the p5 function names and their corresponding module in the p5Modulesmap dictionnary */
    let p5FunctionsModulesmap = new Map()
    for (let x in p5APIModules) {
        p5FunctionsModulesmap.set(p5APIModules[x]["name"],p5APIModules[x]["module"])
    }
    const p5ModulesArray = Array.from(new Set(p5FunctionsModulesmap.values()));
    p5ModulesArray.sort()
    /**
     * store the p5 usage in artwork source code files and their correspinding module  */
    getP5UsageAndModules(p5FunctionsModulesmap, pathsToArtFiles, "p5AndModulesInArtworks74.json")

    /**
     * get and store  p5 usage in artwork source code files in vectors of size = nb p5 functions */
    let p5FunctionsVectorsForAllArtworks=getP5FunctionsVectors(p5map, allpaths, "p5VectorsArtworks.json")

    /**
     * get and store  p5 usage in artwork source code files in vectors of size = nb p5 functions */
    let p5ModulesVectorsForAllArtworks=getP5ModulesVectors(p5FunctionsModulesmap, p5ModulesArray, allpaths, "p5ModulesVectors74Artworks.json")
    
    /**
     * compute a 2D projection of all vectors */
    getembedding(p5FunctionsVectorsForAllArtworks,"artworksEmbedding74.json")

}

/** 
 * This function statically analyses all art files and stores the p5 API usage in a local file
 * @param {Map} p5map. Map that stores the names of all p5 functions 
 * @param {Array} allpaths. An array of paths to artwork source code files 
 * @param {String} p5inart. The name of the file to store the p5 usage of the artworks
 */
function getP5Usage(p5map, allpaths, p5inart) {
    // contains one json object per artwork,  with the list of p5 functions invoked by the artwork
    let p5InAllartworks = []
    for (let f in allpaths) {
        let p5FunctionsInvokedInArtwork = getInvokedP5Functions(allpaths[f], p5map)
        p5InAllartworks.push(p5FunctionsInvokedInArtwork)
    }
    fs.writeFileSync(p5inart, JSON.stringify(p5InAllartworks), function (err) {
        if (err) throw err;
        console.log('complete');
    })
}

/** 
 * This function statically analyses all art files and stores the p5 API usage in a local file
 * @param {Map} p5Modulesmap. Map that stores the names of all p5 functions, with their corresponding module name
 * @param {Array} allpaths. An array of paths to artwork source code files 
 * @param {String} p5AndModulesinart. The name of the file to store the p5 usage of the artworks
 */
function getP5UsageAndModules(p5Modulesmap, allpaths, p5AndModulesinart) {
    // contains one json object per artwork,  with the list of p5 functions invoked by the artwork
    let p5InAllartworks = []
    for (let f in allpaths) {
        let p5FunctionsInvokedInArtwork = getInvokedP5FunctionsAndModules(allpaths[f], p5Modulesmap)
        p5InAllartworks.push(p5FunctionsInvokedInArtwork)
    }
    fs.writeFileSync(p5AndModulesinart, JSON.stringify(p5InAllartworks), function (err) {
        if (err) throw err;
        console.log('complete');
    })
}



/**
 * This function creates one vector per artwork, all of the same size, and stores them on disk in p5vectors
 * @param {Map} p5map. Map that stores the names of all p5 functions 
 * @param {Array} allpaths. An array of paths to artwork source code files 
 * @param {String} p5vectors. The name of the file to store the p5 usage of the artworks 
 * @returns {Array}. An array of vectors that capture the part of the p5 API used by each artwork in allpaths
 */
function getP5FunctionsVectors(p5map, allpaths, p5vectors) {
    // contains one json object per artwork, each object stores the name of the artwork
    // as well as the complete list of functions in the p5 API, and the number of times the artwork invokes them (0 or more)
    let p5VectorsForAllArtworks = []
    for (let f in allpaths) {
        let p5VectorArtwork = getP5FunctionsVector(allpaths[f], p5map)
        p5VectorsForAllArtworks.push(p5VectorArtwork)
    }
    fs.writeFileSync(p5vectors, JSON.stringify(p5VectorsForAllArtworks), function (err) {
        if (err) throw err;
        console.log('complete');
    }
    );
    return p5VectorsForAllArtworks
}

/**
 * This function creates one vector per artwork, all of the same size, and stores them on disk in p5vectors
 * @param {Map} p5FunctionsModulesmap. Map that stores the names of all p5 functions, and their corresponding module 
 * @param {Array} p5ModulesArray. Array with all p5 modules names, in alphabetical order 
 * @param {Array} allpaths. An array of paths to artwork source code files 
 * @param {String} p5vectorsFile. The name of the file to store the p5 usage of the artworks 
 * @returns {Array}. An array of vectors that capture the part of the p5 API used by each artwork in allpaths
 */
function getP5ModulesVectors(p5FunctionsModulesmap, p5ModulesArray, allpaths, p5vectorsFile) {
    // contains one json object per artwork, each object stores the name of the artwork
    // as well as the complete list of functions in the p5 API, and the number of times the artwork invokes them (0 or more)
    let p5ModulesVectorsForAllArtworks = []
    for (let f in allpaths) {
        let p5VectorArtwork = getP5ModulesVector(allpaths[f], p5FunctionsModulesmap, p5ModulesArray)
        p5ModulesVectorsForAllArtworks.push(p5VectorArtwork)
    }
    fs.writeFileSync(p5vectorsFile, JSON.stringify(p5ModulesVectorsForAllArtworks), function (err) {
        if (err) throw err;
        console.log('complete');
    }
    );
    console.log(p5ModulesVectorsForAllArtworks)
    return p5ModulesVectorsForAllArtworks
}


/** This function fetches the names of all p5 methods and stores them in a local file for further usage
 *  The names of the functions are fetched from an online endpoint provided by p5
 *  The names are stored in a local file called p5API.json
 */
async function storeP5API() {
    /*  all p5 elements are documented in a single json object, here: https://p5js.org/reference/data.json
        classitems lists all the methods
    */
    const p5functions = new Map()
    const response = await fetch('https://p5js.org/reference/data.json');
    const p5api = await response.json();
    for (let i in p5api.classitems) {
        if (p5api.classitems[i].itemtype == "method") {
            p5functions.set(p5api.classitems[i].name, i)
            p5functionsnames.push(p5api.classitems[i].name)
        }
    }
    fs.writeFileSync("p5API.json", JSON.stringify(Array.from(p5functions.entries())), function (err) {
        if (err) throw err;
        console.log('complete');
    });
}

/**
 * This function explores folder recursively. If it finds a file, it stores its complete path
 * @param {String} folder. The folder inside which are stored art source code files
 * @returns {Array} paths. An array that stores all the paths to each individual file found in folder 
 */
function getArtFilesInFolder(folder) {
    let filenames = fs.readdirSync(folder);
    let paths = []
    filenames.forEach(file => {
        let stat = fs.statSync(folder + file)
        if (stat.isDirectory()) {
            let path = folder + file + '/'
            getArtFilesInFolder(path)
        }
        else {
            pathsToArtFiles.push(folder + file)
            paths.push(folder + file)
        }
    })
    return paths
}


/* This function is used when the artworks are already annotated with a classification
*/
function getClassification(artwork) {
    const nameWithoutExt = path.parse(artwork).name;

    let classification = []
    for (let c in artwork_classification) {
        if (artwork_classification[c].title == nameWithoutExt) {
            for (let mat in artwork_classification[c].classification.material_and_processes) {
                classification.push(artwork_classification[c].classification.material_and_processes[mat])
            }
            (artwork_classification[c].classification.interaction[0] == "yes") ? classification.push("interactive") : classification.push("non_interactive")
            for (let sense in artwork_classification[c].classification.outcome) {
                classification.push(artwork_classification[c].classification.outcome[sense])

            }
            break
        }
    }
    classification.sort()
    return classification
}

/** 
 * @param {String} filename. Path for one file for an artwrork 
 * @param {Map} p5functions. The list of p5 functions 
 * @returns a JSON object that includes 
 * - "artwork" : the name of the artwork
 * - "p5functions" : an array with the list of p5 functions invoked by the artwork, in alphabetical order 
 * (no duplicate, if a p5 function is invoked multiple times, it appears only once in the array)
 */
function getInvokedP5Functions(filename, p5functions) {
    let acornconfig = {
        ecmaVersion: 9,
        sourceType: "script",
        allowReturnOutsideFunction: true
    }
    let p5FunctionsInFile = [];
    if (getFileExtension(filename) == ".js") { // this condition will skip cases where the art is in html
        const code = fs.readFileSync(filename).toString();
        try {
            const ast = acorn.parse(code, acornconfig).body;
            let functionname, p5function
            recast.visit(
                ast,
                {
                    visitCallExpression: (path) => {
                        functionname = path.node.callee.name
                        p5function = p5functions.has(functionname)
                        if (functionname && p5function && !p5FunctionsInFile.includes(functionname)) {
                            p5FunctionsInFile.push(functionname)
                        }
                        return false;
                    }
                }
            )
        }
        catch (error) {
            if (error instanceof SyntaxError) {
                return {
                    artwork: filename,
                    p5functions: ["parse error"]
                };
            }
            // rethrow unexpected errors
            throw error;
        }
    }
    p5FunctionsInFile.sort() // sort alphabetically to facilitate comparison between artworks
    return { artwork: filename, p5functions: p5FunctionsInFile }
}

/** 
 * @param {String} filename. Path for one file for an artwrork 
 * @param {Map} p5functions. The list of p5 functions and corresponding modules
 * @returns a JSON object that includes 
 * - "artwork" : the name of the artwork
 * - "p5functions" : an array with the list of p5 functions invoked by the artwork, in alphabetical order 
 * - "p5Classes" : an array with the different types of p5 classes that are used by the artwork
 * (no duplicate, if a p5 function is invoked multiple times, it appears only once in the array)
 */
function getInvokedP5FunctionsAndModules(filename, p5modules) {
    let acornconfig = {
        ecmaVersion: 9,
        sourceType: "script",
        allowReturnOutsideFunction: true
    }
    let p5FunctionsInFile = [];
    let p5ModulesInFile = [];

    if (getFileExtension(filename) == ".js") { // this condition will skip cases where the art is in html
        const code = fs.readFileSync(filename).toString();
        try {
            const ast = acorn.parse(code, acornconfig).body;
            let functionname, isp5function
            recast.visit(
                ast,
                {
                    visitCallExpression: (path) => {
                        functionname = path.node.callee.name
                        isp5function = p5modules.has(functionname)
                        if (isp5function && !p5FunctionsInFile.includes(functionname)) {
                            p5FunctionsInFile.push(functionname)
                            if (!p5ModulesInFile.includes(p5modules.get(functionname))){
                                p5ModulesInFile.push(p5modules.get(functionname))
                            }
                        }
                        return false;
                    }
                }
            )
        }
        catch (error) {
            if (error instanceof SyntaxError) {
                return {
                    artwork: filename,
                    p5functions: ["parse error"]
                };
            }
            // rethrow unexpected errors
            throw error;
        }
    }
    p5FunctionsInFile.sort() // sort alphabetically to facilitate comparison between artworks
    p5ModulesInFile.sort() // sort alphabetically to facilitate comparison between artworks
    return { artwork: filename, p5functions: p5FunctionsInFile, p5modules: p5ModulesInFile }
}

function safeParse(code) {
    try {
        const ast = parse(code, {
            ecmaVersion: "latest",
            sourceType: "module"
        });
        return { success: true, ast };
    } catch (error) {
        if (error instanceof SyntaxError) {
            return {
                success: false,
                message: error.message,
                location: {
                    line: error.loc?.line,
                    column: error.loc?.column
                }
            };
        }

        // rethrow unexpected errors
        throw error;
    }
}

// returns one json object for the filename
// filename must be the name of one javascript file (a script)
// the json object includes 
// - "artwork" : the name of the artwork
// - "p5functions" : the key is one p5 method; the value is the number of times the p5 method is invoked in filename
function getP5FunctionsVector(filename, p5functions) {
    const code = fs.readFileSync(filename).toString();
    let acornconfig = {
        ecmaVersion: 9,
        sourceType: "script",
        allowReturnOutsideFunction: true
    }

    let functionname, p5function, p5vector, val
    // initialize a map with all p5 methods as keys, and 0 as value
    p5vector = p5functions
    for (let v of p5vector.entries()) {
        p5vector.set(v[0], 0);
    }
    if (getFileExtension(filename) == ".js") {
        const ast = acorn.parse(code, acornconfig).body;
        recast.visit(
            ast,
            {
                visitCallExpression: (path) => {
                    functionname = path.node.callee.name
                    p5function = p5vector.has(functionname)
                    // if a p5 method is found in the sketch, we increment its corresponding value in p5vector
                    if (functionname && p5function) {
                        val = p5vector.get(functionname)
                        p5vector.set(functionname, val + 1)
                    }
                    return false;
                }
            }
        )
    }
    return { artwork: filename, p5functions: Object.fromEntries(p5vector) }
}

/**
 * 
 * @param {String} filename. path to an artworks source code file 
 * @param {Map} p5functions. map of p5 function names and corresponding module
 * @param {Array} p5ModulesArray. array with names of p5 modules, in alphabetical order
 * @returns a JSON object:
 * - "functionname": path to an artworks source code file
 * - "modulesvector": a key value object: key is the name of a module; value is 1 if artwork relates to that module
 */
function getP5ModulesVector(filename, p5functions, p5ModulesArray) {
    const code = fs.readFileSync(filename).toString();
    let acornconfig = {
        ecmaVersion: 9,
        sourceType: "script",
        allowReturnOutsideFunction: true
    }

    let invokedfunctionname, isp5function, p5ModulesVector, modulename
    p5ModulesVector = new Map()
    for (let m in p5ModulesArray) {
        p5ModulesVector.set(p5ModulesArray[m], 0);
    }
    if (getFileExtension(filename) == ".js") {
        const ast = acorn.parse(code, acornconfig).body;
        recast.visit(
            ast,
            {
                visitCallExpression: (path) => {
                    invokedfunctionname = path.node.callee.name
                    isp5function = p5functions.has(invokedfunctionname)
                    // if a p5 method is found in the sketch, we increment its corresponding value in p5vector
                    if (isp5function) {
                        modulename = p5functions.get(invokedfunctionname)
                        if(p5ModulesVector.get(modulename)==0){
                            p5ModulesVector.set(modulename,1)
                        }
                    }
                    return false;
                }
            }
        )
    }
    return { artwork: filename, p5functions: Object.fromEntries(p5ModulesVector) }
}

/**
 * This function computes a t-SNE embedding of he vectors and stores the coordinates in embeddingFile
 * @param {Array} artworksVectors. An array of vectors. Their length is the number of p5 functions. One vector per artwork. 
 * @param {String} embeddingFile. The name of the file where the 2D coordinates and labels are stored 
 */
function getembedding(artworksVectors, embeddingFile) {
    let data = []
    let labels = []
    let classifications = []
    for (let art in artworksVectors) {
        let onevector = []
        let currentartwork = artworksVectors[art]
        for (let f in currentartwork.p5functions) {
            onevector.push(currentartwork.p5functions[f])
        }
        data.push(onevector)
        labels.push(currentartwork.artwork)
        classifications.push(getClassification(currentartwork.artwork))
    }

    // compute t-SNE in 2D with the vectors, label each point in the 2D space with the corresponding artwork name
    // the coordinates of the points, and their labels, are stored on disk
    const tsne = new druid.TSNE(data, {
        perplexity: 30,
        epsilon: 10,
        d: 2,
        seed: 42
    });
    const embedding = tsne.transform(500); // 500 iterations
    // console.log(embedding)
    // console.log(labels)
    const JSONembed = { "embedding": embedding, "labels": labels, "classifications": classifications }
    fs.writeFileSync(embeddingFile, JSON.stringify(JSONembed), function (err) {
        if (err) throw err;
        console.log('complete');
    })
}

/* input: name of a file
   output: string that corresponds to the extension of the input file, e.g. ".js"
*/
function getFileExtension(filename) {
    var i = filename.lastIndexOf('.');
    return (i < 0) ? '' : filename.substr(i);
}